### ISSUE TITLE
Keyboard tray pops up on iPad even though Bluetooth Keyboard is connected

### ISSUE THREAD

**Issue by brycv** [jcs/endless#11]
If I have a Bluetooth Keyboard (Logitech K811 in this case) connected to my iPad Air 2 running iOS 8.4.1, if I open up DuckDuckGo (or other site which needs text input) and tap in the search field, the keyboard tray pops up into the middle of the screen but where the keyboard would normally be is totally blank. Endless does appear to recognize the Bluetooth Keyboard because I can't scroll back down to see the text input field like I can with the on-screen keyboard. Attached is a screenshot of what it looks like.

![image](https://cloud.githubusercontent.com/assets/891996/9291929/36d36aca-4391-11e5-8bd4-cc44efc8eed5.jpg)

**Comment by jcs** [comment]
I committed something that may fix this but I can't test it because I don't have a bluetooth keyboard.  Are you able to compile this and test locally on your device?

**Comment by brycv** [comment]
Let me see what I can do. I'll attempt to do that. Thanks for the quick response!

**Comment by jcs** [comment]
If you can document what you need to do to get it compiled on a new machine, that would be great.  I'd like to add those instructions to the README so others can compile and test things instead of waiting for me to push production builds through the App Store.

It should be at least:
- `git clone git@github.com:jcs/endless.git`
- `cd endless`
- `pod install` (`sudo gem install cocoapods` if cocoa pods is not installed)
- `open Endless.xcworkspace` (should open in Xcode)

You'll need a valid development certificate to deploy onto your device, but the current Xcode 7 beta allows for "free provisioning" so there must be a way to get a free cert through that (though does it require iOS 9?).

I'm assuming you would click on "Endless (2 targets)" in the menu on the left, then click the Endless target in the "targets" list in the middle, then click the General tab and change the Team dropdown to something else.

**Comment by brycv** [comment]
I'll give that a shot. I was just at the cocoapods issue.

**Comment by brycv** [comment]
I just accepted the latest developer agreement and Apple doesn't seem to recognize this so I can't create a certificate just yet. Hopefully that will resolve shortly. I'm still using Xcode 6.4 at this point. I can switch to Xcode 7 on another system running beta software if I need to.

**Comment by brycv** [comment]
Both bugs I reported are solved by your commits! Thank you! Secondarily, I had a lot of issues with certificates but I'm not sure that has anything to do with what someone else might have to do. The App ID had to be changed for me to compile it (_org.jcs.endless_ was taken obviously) and I had to use my own Team and so forth. I also had to add the Data Protection Entitlement under Capabilities for the certificate to generate properly (a warning was displayed that I finally located). The other steps you wrote above worked fine. I'll see if I can setup a new environment and go through this start to finish and see if I will still have problems with it.

Also, are you using TestFlight at all for Endless?

**Comment by jcs** [comment]
Thanks for testing.  I'm going to close this bug since it is resolved, but if you want to continue with documenting the build process from scratch, please feel free to open a new issue.

I am not using TestFlight for Endless at this time.  Pushing a new build to an external beta list still requires approval from Apple, so there's like a 2-4 day delay between submitting a build and getting it out.  I'm too impatient to do that each time.
