### ISSUE TITLE
m.facebook.com/messages not working

### ISSUE THREAD

**Issue by QQQNo** [jcs/endless#28]
It's impossible to access the mobile facebook messages, as an alternative to the Messenger app. 

mbasic.facebook.com works, but it's quite ugly.

**Comment by jcs** [comment]
I spent quite a bit of time debugging this and I can't seem to figure out what's causing the login failure.  If `DummyURLInterceptor` is enabled, it works fine.  Disabling everything in `URLInterceptor` like HTTPSEverywhere, HSTS, custom cookie handling, Javascript injection, etc. still doesn't work.

From inspecting the site's JSContext in Safari and watching the requests, everything is the same between the two as it makes the initial request, loads the many CSS and Javascript assets, but at the end when `URLInterceptor` does an Ajax call to `https://m.facebook.com/a/bz` (before attempting to actually login), Facebook's server returns a big HTML page with `Content Not Found` (despite a 200 status code) instead of a small bit of Javascript, which is what `DummyURLInterceptor` gets.  I can't see any difference in the headers/data sent between the two (modulo some random session data).

I modified `URLInterceptor` to keep all of its addons (except TLS cipher modification) but not drop down to `CKHTTPConnection` and just use a normal `NSURLConnection`, and it does work.  This would point to a problem in `CKHTTPConnection` somewhere but I tried keeping it and disabling all of its TLS adjustments and gzip handling, and it is still broken.

**Comment by QQQNo** [comment]
No worries, thanks a lot for investigating, though! I'm pretty sure it worked for a few minutes a week ago, suddenly it didn't. IIRC there was a popup by them, telling me to use their app instead. It worked for a little bit after. I couldn't reproduce this when I deleted and reinstalled Endless today, though.
